[project]
name = "asset-management"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.1",
    "django-debug-toolbar>=6.1.0",
    "psycopg2-binary>=2.9.11",
]
